### ISSUE TITLE
Automatic memory release has a problem.

### ISSUE THREAD

**Issue by hamoumiKen** [CodeDead/MemPlus#13] opened 2022-10-30 13:38 UTC
MemPlus' automatic memory release has a problem: it can only automatically release memory once. When memory is released after a set time, the software will somehow exit at the same time as the automatic memory release if the software is resident.

The automatic memory release function is somewhat difficult to use because you have to manually start the software again.

**Comment by CodeDead** [comment] 2022-11-03 05:41
I believe this to be a duplicate of https://github.com/CodeDead/MemPlus/issues/9

This was fixed in commit
https://github.com/CodeDead/MemPlus/commit/d7491011352bf6de3f1e0db07995f00edb409f51

A new release has yet to be delivered.

**Closed as completed by CodeDead** 2022-11-03 05:41 UTC
Labels: duplicate
